name: odak_list
description: "CoFocus: Team Collaboration and Task Management App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # --- UYUMLU PAKET LİSTESİ ---
  
  # sqflite 2.3.0 yerine 2.3.2 sürümünü kullanıyoruz (Daha kararlı)
  # sqflite: ^2.3.2
  
  path: ^1.9.0
  intl: ^0.19.0
  
  # Bildirimler için güvenli sürüm
  flutter_local_notifications: ^17.1.0
  
  timezone: ^0.9.2
  
  # Timezone hatasını çözen sürüm
  flutter_timezone: ^3.0.1 
  
  # path_provider SDK 34 ile uyumlu sürüm
  path_provider: ^2.1.2
  
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  audioplayers: ^6.0.0
  share_plus: ^10.0.0 
  file_picker: ^8.0.0
  home_widget: ^0.8.1
  # Wakelock'u güncelledik (Eskiden 1.1.2 idi, 1.2.0 yaptık)
  wakelock_plus: 1.2.0

  firebase_core: ^2.27.0  # Firebase Beyni
  firebase_auth: ^4.17.8  # Giriş/Kayıt işlemleri
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19

  firebase_storage: ^11.6.0 # Dosya depolama
  cached_network_image: ^3.3.1 # Resimleri hızlı yüklemek için (Opsiyonel ama önerilir)
  purchases_flutter: ^8.0.0
  # Speech to text (Hata verirse 6.3.0'a çekeriz ama şimdilik kalsın)
 # speech_to_text: ^6.6.2

# --- SORUN ÇÖZÜCÜ KISIM ---
dependency_overrides:
  # Android SDK 34 (Android 14) ile uyumlu çalışması için
  # bu özel versiyonları zorluyoruz:
  path_provider_android: 2.2.5
  sqflite_android: 2.4.1
  shared_preferences_android: 2.3.2
  flutter_plugin_android_lifecycle: 2.0.22
  package_info_plus: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Dosyanın burada olduğundan %100 emin ol
  min_sdk_android: 21
  adaptive_icon_background: "#FE806F"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#0A192F" # Arka plan (Senin widget rengin)
  image: assets/icon.png # İkonun yolu
  android_12:
    image: assets/icon.png
    color: "#0A192F"